before_install:
  - date
  - cat /proc/cpuinfo
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install libgc-dev libgmp-dev make bc fakeroot kernel-package gcc-4.8 binutils
  - cd /usr/bin && sudo ln -sf gcc-4.8 gcc
  - export NUMCPU=`grep -c "^processor" < /proc/cpuinfo`
  # Seting-up ATS2-contrib
  - cd ${HOME}
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  # Building ATS2
  - cd ${HOME}
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-srcfrg
  - export PATSHOME=${HOME}/ATS2-srcfrg
  - export PATH=${PATH}:${PATSHOME}/bin
  - cd ${PATSHOME} && ./configure && make
  # Show the toolchain version
  - patsopt --version
  - gcc --version
  - ld -version
script:
  - cd ${TRAVIS_BUILD_DIR}
  - cp metasepi/linux.config ./.config
  - yes "" | make oldconfig
  - make -j ${NUMCPU} | grep -v ' CC '
after_script:
  - date
