#ifndef _METASEPI_FS_BTRFS_TESTS_CATS_BTRFS_TESTS_CATS
#define _METASEPI_FS_BTRFS_TESTS_CATS_BTRFS_TESTS_CATS

#include <fs/btrfs/tests/btrfs-tests.h>

#endif /* _METASEPI_FS_BTRFS_TESTS_CATS_BTRFS_TESTS_CATS */
